[project]
name = "nonebot-plugin-arkgacha"
version = "0.3.0"
description = "Plugin for Arknights gacha, support multi platform"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-plugin-alconna>=0.7.0",
    "nonebot-plugin-send-anything-anywhere>=0.2.4",
    "arknights-toolkit<0.6.0, >=0.5.8",
    "nonebot-plugin-localstore>=0.4.1",
    "nonebot-plugin-apscheduler>=0.2.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.build]
includes = ["nonebot_plugin_arkgacha"]