[project]
name = "nonebot-plugin-arkgacha"
version = "0.1.3"
description = "Plugin for Arknights gacha, support multi platform"
authors = [
    {name = "RF-Tar-Railt", email = "3165388245@qq.com"},
]
dependencies = [
    "nonebot2>=2.0.0rc4",
    "nonebot-plugin-alconna>=0.4.2",
    "nonebot-plugin-send-anything-anywhere>=0.2.4",
    "arknights-toolkit>=0.5.2",
    "nonebot-plugin-localstore>=0.4.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.build]
includes = ["nonebot_plugin_arkgacha"]